### ISSUE TITLE
закройте ето

### ISSUE THREAD

**Issue by proma462346** [SkiTles55/SPT-AKI-Profile-Editor#59]

**Comment by proma462346** [comment]
1

**Comment by SkiTles55** [comment]
Оригинальное сообщение автора до редактирования (просто для истории, и смеха):

Versions

SPT-AKI Server version 2 2 3 7
SPT-AKI Profile Editor version (пробовал версии от 1.9-2.4) но последняя версия работает только нету добовления предметов
Describe the bug
A clear and concise description of what the bug is.
изображение
Additional context
SPT-AKI Profile file (не требуетца)
Just create zip archive with your profile file and drag'n'drop here. Bug reports without attached profile file will be closed without any help if they related to user profile
(я указивал разние папки как в таркове так и саму папку таркова не помогает)
